### ISSUE TITLE
Export Cmdlet not working for SharePoint 2010

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#216]
#### Category

- [X] Bug
- [ ] Enhancement

#### Problem Area

- [ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
- [X] Page Transformation: Error during the use of page transformation from PnP PowerShell
- [ ] Page Transformation: Error during the use of page transformation from .Net
- [ ] Page Transformation: Page is not looking correct after transformation
- [ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

It produces mapping files.

#### Observed Behavior

GetList not supported in CSOM for SharePoint 2010

#### Steps to Reproduce
```powershell
$sourceConn = Connect-PnPOnline http://portal2010 -ReturnConnection
Export-PnPClientSidePageMapping -PublishingPage "Article-2010-Custom.aspx" -CustomPageLayoutMapping -Connection $sourceConn -Folder (Get-Location)
```

I didn't realise the PnP PowerShell release would come this early, need to test the other cmdlets.
@jansenbe please assign to me - should I raise this in PnP-PowerShell project?

**Comment by pkbullock** [comment]
Also, I would like to submit a change in the cmdlet to default the output to the current working directory, I'm super lazy  and didn't want to keep adding "-Folder (Get-Location)" each time I used the command.

**Comment by jansenbe** [comment]
Hi @pkbullock ,

GetList is indeed used in PagePipeBind.cs. I've already done some changes to support 2010, but as I'm not having a 2010 lab yet you would need to cross check and finalize these:

In **Modernization**
- Added GetListByName extension method that should work in 2010
- Updated GetPublishingPagesLibraryName method to use a different code path for 2010 as that requires more server roundtrips. Also fixed the missing ServerRelativeUrl load in the 2010 approach

In **PowerShell**
- Updated PagePipeBind.cs to use the new GetListByName method
- Removed the temp ServerRelativeUrl load I added to quickly fix this after we've released the August version

Might be that more changes are needed in PS to support 2010, let me know if you need some help with building and testing PS from our dev branch.

**Comment by jansenbe** [comment]
About the -Folder: you don't need to specify this parameter at all...only needed if you're targeting a page that lives in specific folder inside your library.

**Comment by pkbullock** [comment]
lol just started working on this, glad i didnt get to far, will go with your code and test 😊

**Comment by pkbullock** [comment]
hey @jansenbe still getting issues with PnP transform for ConvertTo command, just wondering for tomorrows call we should mention we are working on 2010 support. Btw, Export-PnPClientSidePageMapping  works in my test. Ill open a new issue for the record.
