### ISSUE TITLE
_Field or property "ExportMode" does not exist for Custom webparts in a custom page layout of the Publishing Page

### ISSUE THREAD

**Issue by KVSolutions** [SharePoint/sp-dev-modernization#265]
#### Category

[ X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Publishing page with custom page layout and has custom webparts should be migrated successfully

#### Observed Behavior
Publishing Page with custom web parts are throwing an error "_Field or Property 'Export mode' does not exist" observed with Sep2019 release (3.13.1909.0)

#### Steps to Reproduce
Publishing page with custom page layout and custom webparts has been throwing this issue

**Here is the stack trace**
_Field or property "ExportMode" does not exist.   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientObjectExtensions.<EnsurePropertiesImplementation>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperties[T](T clientObject, Expression`1[] propertySelector)
   at SharePointPnP.Modernization.Framework.Pages.BasePage.LoadWebPartsInWikiContentFromServer(List`1 webparts, File wikiPage, List`1 webPartsToRetrieve)
   at SharePointPnP.Modernization.Framework.Pages.PublishingPageOnPremises.Analyze(PageLayout publishingPageTransformationModel)
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)_

**Comment by KVSolutions** [comment]
> Hi @jansenbe 
> 
> What is the SharePoint version of your on-premises environment?
Its SharePoint 2013
> Does the problem apply to all pages or just some? If some is there any specific web part that all these pages share?
I`m trying a POC to see ,how the migration of all the pages will go.Not all pages share this custom webpart,few of the pages has this webpart.
> Are the web parts added into a web part zone or embedded in the main edit area? If not in a web part zone can you try converting a page with the same web part in a web part zone on the publishing page?
The webparts are embedded in Rich Text field of Publishing page content of main edit area,I cant try converting this webpart with in a webpart zone as this page layout doesn`t have any webpart zones.there are some hardcoded webparts on the layout.

**Comment by pkbullock** [comment]
The provided error message is very useful in pinpointing the issue, Custom Web Parts in Wiki Content Pages with on-premises transform.  

I have a feeling this might be a gap in features, my test rigs do not contain that scenario, would need to to write custom web parts for each version of SharePoint to be thorough. Its likely easy to fix as the modifications for supplementing via web services have formed a code pattern in these cases, just testing them which takes longer.

**Comment by jansenbe** [comment]
Indeed @pkbullock : the code path to retrieve web parts when in a wiki content section of a publishing page is using the "SPO" logic and and not the "on-prem" logic for web part retrieval.

**Comment by jansenbe** [comment]
@pkbullock  / @KVSolutions :
I can repro this by putting a web part in a wiki text zone...will work on a fix

**Comment by jansenbe** [comment]
Fixed. Will be part of the October release (release date around October 4th).

**Comment by jansenbe** [comment]
@KVSolutions : if you're transforming via .Net you could pull down the code and compile your own version of the page transformation engine. If you're using PowerShell things are slightly more complex as you'll need to also build a dev version from PnP PowerShell as well.

**Comment by jansenbe** [comment]
Closing this issue since the fix is in. Let me know if you still see issues when using the latest

**Comment by paylord** [comment]
I have just updated to 3.14.1910 and I am still seeing this error on selected pages.  The source is SP2013.  The only web part on one of them is a Summary Links which links to people.  The only common factor I can see is the page is split 2/3 - 1/3 (One column with sidebar from text layout option).

**Comment by paylord** [comment]
My issue is actually for team site pages and not publishing pages - please let me know if you prefer this to be raised as a new issue?

I have around 200 pages in SP2013 and just less than half failed.  All the ones I have checked so far had the split text layout.

Stack Trace:
_Field or property "ExportMode" does not exist.   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientObjectExtensions.<EnsurePropertiesImplementation>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperties[T](T clientObject, Expression`1[] propertySelector)
   at SharePointPnP.Modernization.Framework.Pages.BasePage.LoadWebPartsInWikiContentFromServer(List`1 webparts, File wikiPage, List`1 webPartsToRetrieve)
   at SharePointPnP.Modernization.Framework.Pages.WikiPage.Analyze(Boolean isBlogPage)
   at SharePointPnP.Modernization.Framework.Transform.PageTransformator.Transform(PageTransformationInformation pageTransformationInformation)_

**Comment by paylord** [comment]
Meh - this is trying to take content directly from a SP2013 team site to a modern SPO team site.  I have tried again going via a classic SPO team site and do not get the same errors.

**Comment by jansenbe** [comment]
Hi @paylord ,

There was a fix for this in the intermediate October release (see https://www.powershellgallery.com/packages/SharePointPnPPowerShellOnline/3.14.1910.1). Please open a new issue if you can still repro the problem with that version. Thanks for testing this.
